function createfigure(r, g, b, I)
%CREATEFIGURE(r, g, b, I)
%  r:  image cdata
%  g:  image cdata
%  b:  image cdata
%  I:  image cdata

%  Auto-generated by MATLAB on 20-Feb-2018 15:16:02

% Create figure
figure1 = figure('Name','Figuras');
colormap(gray);

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create image
image(r,'Parent',subplot1,'CDataMapping','scaled');

% Create xlabel
xlabel('rojo');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 2810.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 2455.5]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'Layer','top');
% Create colorbar
colorbar('peer',subplot1);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create image
image(g,'Parent',subplot2,'CDataMapping','scaled');

% Create xlabel
xlabel('verde');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.5 2810.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.5 2455.5]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'Layer','top');
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create image
image(b,'Parent',subplot3,'CDataMapping','scaled');

% Create xlabel
xlabel('azul');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0.5 2810.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0.5 2455.5]);
box(subplot3,'on');
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'Layer','top');
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create image
image(I,'Parent',subplot4,'CDataMapping','scaled');

% Create xlabel
xlabel('original');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0.5 2810.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0.5 2455.5]);
box(subplot4,'on');
axis(subplot4,'ij');
% Set the remaining axes properties
set(subplot4,'Layer','top');
